### PR TITLE
NMI (soft reset) control code enablement

### PR DESCRIPTION
**Pull request by lkammath**
https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-proc-control/+/22193/

Changes here include:
   1) A service that triggers Open BMC App (openpower-proc-nmi)
   2) An application that waits for a dbus event (NMI) to occur
   3) A reset logic that triggers a NMI/softreset dbus service which
      will invoke pdbg call to trigger stop followed by sreset on all
      threads
   4) Necessary Makefile.am changes

Tested: Verified following
 1) openpower-proc-nmi app is automatically started once host is started
 2) After killing the app made sure app is restarted successfully
 3) Verified NMI is detected on the Host side and crash dump being
    collected in /var/crash/ and taking a watchdog triggered reboot
 4) System coming back to original state once all #3 is completed
 5) Powered off the system (obmcutil poweroff) service disabled and
    enabled after host is powered on

Signed-off-by: Lakshminarayana R. Kammath <lkammath@in.ibm.com>
Change-Id: I16f3bb2a2ed0c0ffcea2a720a2ae39a2b303ef9e

### CODE REVIEW

**Comment by geissonator** [comment]
Don't see any files associated with this PR?

**Comment by lkammath** [comment]
> 
> 
> Don't see any files associated with this PR?

I see them

**Comment by geissonator** [comment]
https://github.com/ibm-openbmc/openpower-proc-control/pull/1/files shows no files

**Comment by lkammath** [comment]
I see that all my changes are already OP940 branch already. Not sure how did it get in .. but all the changes are already there ..

**Pull request closed without merging**
